version: '3.8'


services:
  filestorage_db:
    image: postgres:15.3-alpine
    container_name: filestorage-db
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - filestorage_db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: unless-stopped

  filestorage_redis:
    image: redis:alpine
    container_name: filestorage-redis
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - filestorage_redis_volume:/data
    restart: unless-stopped
    depends_on:
      - filestorage_db

  minio:
    image: quay.io/minio/minio:latest
    container_name: filestorage-minio
    env_file:
      - ./.env
    volumes:
      # - /docker/minio:/data
      - minio_volume:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    restart: unless-stopped


  # backend_app:
  #   build: ./dockerization/.
  #   container_name: backend-app
  #   volumes:
  #     - .:/urls_app/
  #   ports:
  #     - '127.0.0.1:8000:8000'
  #   command: >
  #     sh -c "cd ./src/ && alembic upgrade head && python main.py"
  #   depends_on:
  #     - urls_db
  #   env_file:
  #     - ./.env
  #   restart: unless-stopped

volumes:
  filestorage_db_volume:
  filestorage_redis_volume:
  minio_volume:
