version: '3.8'


services:
  filestorage_db:
    image: postgres:15.3-alpine
    container_name: filestorage-db
    volumes:
      - filestorage_db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: unless-stopped

  filestorage_redis:
    image: redis:alpine
    container_name: filestorage-redis
    volumes:
      - filestorage_redis_volume:/data
    depends_on:
      - filestorage_db
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: filestorage-minio
    env_file:
      - ./.env
    volumes:
      - minio_volume:/data
    ports:
      - "${MINIO_SERVICE_PORT:-9000}:9000"
      - "${MINIO_PUBLIC_PORT:-9001}:9001"
    command: server /data --console-address ":9001"
    depends_on:
      - filestorage_redis
    restart: unless-stopped

  backend_app:
    build: .
    container_name: backend-app
    volumes:
      - .:/file_storage_app/
    command: >
      sh -c "cd ./src/ && alembic upgrade head &&
            python -m gunicorn --name file_storage -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:8000 main:app"
    env_file:
      - ./.env
    depends_on:
      - filestorage_db
      - filestorage_redis
      - minio
    restart: unless-stopped

  filestorage_nginx:
    image: nginx:1.24.0-alpine
    container_name: filestorage-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_PUBLIC_PORT:-8095}:80"
    depends_on:
      - backend_app
    restart: unless-stopped

volumes:
  filestorage_db_volume:
  filestorage_redis_volume:
  minio_volume:
