"""02-file_model

Revision ID: 7c20df5c2979
Revises: 96c6ea0d3a8b
Create Date: 2023-11-13 20:30:27.823455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c20df5c2979'
down_revision: Union[str, None] = '96c6ea0d3a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_created_at'), 'uploaded_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_deleted_at'), 'uploaded_files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_updated_at'), 'uploaded_files', ['updated_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_version_id'), 'uploaded_files', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_version_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_updated_at'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_deleted_at'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_created_at'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
